version: "2.3"
services:
  minecraft-modded-server:
    # volumes:
      # https://github.com/docker/compose/issues/3270
      # - ~/volumes/minecraft-server/server:/opt/minecraft/server:Z
      # - ~/volumes/minecraft-server/server_nether:/opt/minecraft/server_nether:Z
      # - ~/volumes/minecraft-server/server_the_end:/opt/minecraft/server_the_end:Z
    cpuset: 0-1
    mem_reservation: 2048m
    build:
      context: .
    ports:
      - "25565:25565"
      - "25575:25575"
